name: Call Reusable Update Workflow

on:
  push:
    branches: [main]

jobs:
  call-update-workflow:
    uses: AhmedSarhanDL/.github/.github/workflows/update-root-project.yml@main
    with:
      service-name: tutor_chat
      commit-sha: ${{ github.sha }}
    secrets:
      ROOT_REPO_TOKEN: ${{ secrets.ROOT_REPO_TOKEN }} 