name: Update Root Project

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - '.github/workflows/update-root.yml'
  workflow_dispatch:  # Allow manual trigger

jobs:
  update-root:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for accurate change detection

    - name: Check for significant changes
      id: check-changes
      run: |
        # Get the files changed in the last commit
        CHANGED_FILES=$(git diff-tree --no-commit-id --name-only -r HEAD)
        
        # Check if any non-docs files were changed
        if echo "$CHANGED_FILES" | grep -qvE '\.(md|txt)$'; then
          echo "significant_changes=true" >> $GITHUB_OUTPUT
        else
          echo "significant_changes=false" >> $GITHUB_OUTPUT
        fi

    - name: Update Root Project
      if: steps.check-changes.outputs.significant_changes == 'true'
      env:
        ROOT_REPO_TOKEN: ${{ secrets.ROOT_REPO_TOKEN }}
        ROOT_REPO: ${{ secrets.ROOT_REPO }}  # Should be in format: owner/repo
        SERVICE_NAME: tutor_chat  # Changed to tutor_chat
      run: |
        ./.github/scripts/update-root.sh

    - name: Handle Script Failure
      if: failure()
      run: |
        echo "::error::Failed to update root project. Please update manually or check if ROOT_REPO_TOKEN and ROOT_REPO secrets are set correctly." 